# Patch file for Keen - use with CK5PATCH.EXE

%ext ck5

%gamemaps custmaps.ck5
%maphead maphead.ck5
%level.name 0 Address Unknown
%level.entry 0 Meat Mirror and \n the Flamingo

%level.name 1 Begin
%level.entry 1 Intro

%level.name 2 Rocket
%level.entry 2 Keen blasts into \n the rocket

%level.name 3 The Tower of Secrets
%level.entry 3 Keen descends the \n Tower of Secrets

%level.name 4 Candy hive
%level.entry 4 Keen buzzes \n into the Candy hive

%level.name 5 Mortillery
%level.entry 5 Keen invades the \n Mortillery

%level.name 6 Volte-A-Pede
%level.entry 6 Keen guides the \n Volte-A-Pede

%level.name 7 ** WILD **
%level.entry 7 Keen's gone WILD!!

%level.name 8 Binary Exit
%level.entry 8 Keen chooses \n the High Bits
             
%level.name 9 Sparky home
%level.entry 9 Keen terrorizes \n the Sparkies' home

%level.name 10 Slicestar \n Guard District
%level.entry 10 Keen cautiously \n enters the SGD

%level.name 11 The House \n of Doors
%level.entry 11 Keen is unable to \n resist entering

%level.name 12 Keen Asylum
%level.entry 12 The very end of Keen

%level.name 13 Invisibility
%level.entry 13 Keen carefully \n trods invisibility

%level.name 14 Robo Pantry
%level.entry 14 Keen robs the \n Robo Pantry
              
%end
